# This action runs on a local github runner
# See https://jano.dev/programming/2022/04/15/local-spm-ga.html

name: Swift
on: [push]
jobs:
  build:
    name: Build
    runs-on: [self-hosted]
    env: 
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Build Package
        run: swift build -v